imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator: { fallbacks: [en] }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection:
      enabled:       false
    validation:      { enabled: true, enable_annotations: false }
    templating:
        engines: ['twig']
        assets_version: 0
    default_locale:  "%locale%"
    trusted_proxies: ~
    trusted_hosts: ~
    session:
        handler_id: session.handler.pdo
    fragments:       ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        main_host: %host%

#Assetic Configuration
parameters:
    # Assetic
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /
    assetic.filter.compass.generated_images_path: '%kernel.root_dir%/../web/images/sprites'
    assetic.filter.compass.http_generated_images_path: '/images/sprites'

assetic:
    debug:          %kernel.debug%
    bundles:        [ AppBundle ]
    filters:
        cssrewrite: ~
        yui_css:
           jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
           jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        closure:
           jar: %kernel.root_dir%/Resources/java/compiler.jar
        scss: ~
        sass: ~
        compass:
          bin: /usr/local/bin/compass

monolog:
    handlers:
        main:
            type:  syslog
            level: info

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

doctrine:
  dbal:
    driver:   '%database_driver%'
    host:     '%database_host%'
    dbname:   '%database_name%'
    user:     '%database_user%'
    password: '%database_password%'
  orm:
    auto_mapping: true

gos_web_socket:
  client:
    firewall: secured_area
    session_handler: @session.handler.pdo
  server:
    port: %ws_port%
    host: %ws_host%
    router:
      resources:
        - '@AppBundle/Resources/config/pubsub/routing.yml'