parameters:
  admin_pass:        admin
  database_driver:   mysql
  database_host:     127.0.0.1
  database_port:     ~
  database_name:     db_name
  database_user:     root
  database_password:

  mailer_transport:  smtp
  mailer_host:       127.0.0.1
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            very_secret

  session_expire: 31536000

  host: chat.alexdevid.ru
  cookie_host: chat.alexdevid.ru
