parameters:
  admin_pass:        admin
  database_driver:   mysql
  database_host:     127.0.0.1
  database_port:     ~
  database_name:     dev_chat
  database_user:     root
  database_password: 5143

  mailer_transport:  smtp
  mailer_host:       127.0.0.1
  mailer_user:       ~
  mailer_password:   ~

  locale:            ru
  secret:            very_secret

  memcache_host: 127.0.0.1
  memcache_port: 11211

  session_expire: 31536000

  host: localhost
  cookie_host: localhost

  ws_port: 1337
  ws_host: localhost