app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_registration_register:
    methods: [GET, POST]
    path: /registration
    defaults:  { _controller: FOSUserBundle:Registration:register }

