security:
  encoders:
    AppBundle\Entity\User: bcrypt

  providers:
    in_memory:
      memory: ~

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      form_login:
        login_path: login
        check_path: login
        always_use_default_target_path: true
    default:
      anonymous: ~