security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
  providers:
    in_memory:
      memory:
        users:
          admin:
            password: %admin_pass%
            roles: 'ROLE_ADMIN'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    default:
      anonymous: ~
      http_basic: ~

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }