services:
  acme_hello.topic_sample_service:
    class: AppBundle\Service\ChatTopic
    tags:
      - { name: gos_web_socket.topic }

  acme_hello.rpc_sample_service:
    class: AppBundle\Service\ChatService
    tags:
      - { name: gos_web_socket.rpc }